import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/providers";
import { Toaster } from "sonner";
import { SheetProvider } from "@/providers/sheet-provider";

export const metadata: Metadata = {
  title: "Auto peças serginho",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster />
          <SheetProvider />
          {children}
        </Providers>
      </body>
    </html>
  );
}
